### ISSUE TITLE
EmptyClassInspection should ignore JSP files

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#10]
If I enable Class structure inspections, it shows that no class is declared:
![jsp_class_structure_inspections](https://user-images.githubusercontent.com/16825982/27317793-7eed95ec-5591-11e7-88eb-ee3412e2aa79.png)

Though JSP is implicit JspServlet class declaration (<!%...%> is within this class body, <%...%> is within JspServlet.service, <%=...%> is withing JspServlet.service() {... out.print(...); ...}.

**Comment by VISTALL** [comment]
Can you show me - that you enabled?

**Comment by unv-unv** [comment]
Analyze > Inspect Code > Inspection profile > ... > Class structure (checked).

**Comment by VISTALL** [comment]
Found issue it's Empty Class Inspection. Need disable it for JSP
