### ISSUE TITLE
Support for JSP include directive

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#11]
[Include directive](https://docs.oracle.com/javaee/5/tutorial/doc/bnajb.html) puts contents of another file into this location. Example of JSP file equal to test.jsp:
<%@ include file="test.jsp"%>

**Comment by VISTALL** [comment]
Oh. Fully forgot about that. Not easy fix - i will think about it.

Thanks

**Comment by VISTALL** [comment]
Can you provide some example of this? (when need not only **navigate to file** from tag)?

**Comment by unv-unv** [comment]
One obscure usage:

foo.jsp:
`<% out.print("foo"); %>`

bar.jsp:
```
<%
if (false)
{
%><%@ include file="foo.jsp"%><%
}
out.print("bar");
%>
```

bar.jsp prints "bar" (not "foobar"!) since printing "foo" is enclosed into if (false) block.

**Comment by unv-unv** [comment]
Real-world example is printing header/footer.

**Comment by VISTALL** [comment]
Now it's navigatable.

**Comment by unv-unv** [comment]
Not just navigatable case (real example simplified): using other JSP file declarations:

foo.jsp:
```
<%!
public static class Foo
{
    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
```

bar.jsp:
```
<%@ include file="foo.jsp"%>
<%
    out.print(Foo.HTML);
%>
```

**Comment by VISTALL** [comment]
Please create new issues with that. Thanks
