### ISSUE TITLE
Public static subclass highlighted as error

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#12]
Subclass of any subclass of JspServlet is highlighted with error:
![jsp_public_static_subsubclass](https://user-images.githubusercontent.com/16825982/27319145-b93738a0-5598-11e7-8975-5af29b6f142e.png)

Code sample (test.jsp):
```
<%@ page import="
    java.lang.*,
    java.lang.reflect.*,
    java.io.*
"%>
<%!
public abstract static class Test
{
    public static class Foo
    {
    }

    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
<%
    out.print(Test.HTML);
%>
<html>
<head><title>Hello, World!</title></head>
<body><div>Hello, World!</div></body>
</html>
```

**Comment by unv-unv** [comment]
After some time highlighting is mystically reversed without changes in source code - outer class is highlighted instead of inner class:
![jsp_public_static_subsubclass_2](https://user-images.githubusercontent.com/16825982/27319467-47c378da-559a-11e7-90f0-d76f0b179da1.png)

**Comment by VISTALL** [comment]
Yeah, i saw this bug. I think it will disapear when i fix modifier issue

**Comment by VISTALL** [comment]
just interest - what frameworks you using in your jsp project?

**Comment by unv-unv** [comment]
In my own JSP project I use only JavaEE libraries with Apache POI for generating excel sheets. Except for these, everything is self-written.
