### ISSUE TITLE
Complex case of JSP include directive

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#13]
Not just navigatable case (real example simplified): using other JSP file declarations:

foo.jsp:
```
<%!
public static class Foo
{
    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
```

bar.jsp:
```
<%@ include file="foo.jsp"%>
<%
    out.print(Foo.HTML);
%>
```

**Comment by unv-unv** [comment]
Include directive is highlighted as erro (JavaEE 2718):
![jsp_include_error](https://user-images.githubusercontent.com/16825982/27399085-53a9c1ba-56c4-11e7-867a-d86dbd2f06df.png)

**Comment by VISTALL** [comment]
extracted https://github.com/consulo/consulo-javaee/issues/14
