### ISSUE TITLE
Wrong highlight for include directive 

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-javaee#14]
![](https://user-images.githubusercontent.com/16825982/27399085-53a9c1ba-56c4-11e7-867a-d86dbd2f06df.png)

**Comment by unv-unv** [comment]
In JavaEE 2847 include still highlighted red. Mouse over says "Cannot resolve symbol 'include'".

**Comment by VISTALL** [comment]
Can't reproduce

**Comment by unv-unv** [comment]
Ah, I see - it's my specific case. Will open another issue.
