### ISSUE TITLE
Web Resources folder names delimiter should be slash

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#16]
Consulo collapses chain of empty packages in Sources folder using dot as delimiter. For Web Resources delimiter should be a forward slash:
![jsp_folder_names_delimiter_should_be_slash](https://user-images.githubusercontent.com/16825982/27635539-1c44a590-5c10-11e7-800c-b99c49d62d0a.png)

**Comment by VISTALL** [comment]
Flatten packages shound skip this source roots (no flatten for web roots)

**Comment by VISTALL** [comment]
This bug exists in **resources roots* too
