### ISSUE TITLE
Implementing non-static interface by static class in JSP highlighted as error

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#17]
Implementing non-static interface by static class in JSP highlighted as error:
![jsp_non_static_interface_error](https://user-images.githubusercontent.com/16825982/27675230-d0114c12-5cb1-11e7-93d0-4deb7cd5c7c6.png)

If I mark interface Foo in above example as static error goes away. Though static keyword for inner interface is redundant (https://stackoverflow.com/questions/71625/why-would-a-static-nested-interface-be-used-in-java).

This error is not shown if interface and implementing class is enclosed into another class. So it must be some problem in JSP parser itself (treating implicit enclosing JSP class somehow incorrectly).

**Comment by VISTALL** [comment]
Same in IDEA

![](http://klikr.org/681566bad869f7249b21c6e7a258.png)

**Comment by unv-unv** [comment]
Java spec [says](http://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.5.1):
> A member interface is implicitly static (§9.1.1). It is permitted for the declaration of a member interface to redundantly specify the static modifier.

So it's a bug in IDEA. Since interface Foo is an inner interface of outer JSP class.

**Comment by VISTALL** [comment]
this bug fixed in java plugin
