### ISSUE TITLE
Public static inner class not allowed in JSP

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#18]
Public static inner class is highlighted as error: "modifier 'public' not allowed here":
![jsp_public_static_subsubclass_not_allowed](https://user-images.githubusercontent.com/16825982/27676731-c3135f86-5cb7-11e7-9f38-cfcd60c9759b.png)

**Comment by VISTALL** [comment]
![](http://klikr.org/eb81da346fde8a89a2e378f035ba.png)

It's ok. But parent **public** is not highlighted

**Comment by VISTALL** [comment]
my bad

**Comment by VISTALL** [comment]
It's inner class 

![](http://klikr.org/1a37848bbc03c78102eec3cc010d.png)

Valid

**Comment by unv-unv** [comment]
In your example there's a static nested class inside of non-static one. In my example it's a static class Test (technically static nested class inside JSP outer class) with static nested class Bar.

Anyway, I found no evidence in specs that public modifier should be omitted in such a case.

**Comment by VISTALL** [comment]
Same error
![](http://klikr.org/3e7e9492f87f04b11be6985f391c.png)

We are searching bugs in idea ? 🤐

**Comment by VISTALL** [comment]
I have an another question. How you run jsp files ?( from consulo - apache tomcat for example)

**Comment by unv-unv** [comment]
Apache Tomcat, JBoss for my own projects locally (Win10). WebLogic and Jboss on remote servers (SSH/Linux) for corporative tasks.

I didn't yet set up server start from Consulo - just copying pages by hands.

**Comment by VISTALL** [comment]
Consulo had some support for tomcat - but it's awful (no requests for improve it - but i planed to improve it, because i need it for "Consulo as web service support" development process)

**Comment by unv-unv** [comment]
Understood. I'll try to help with requests after JSP pages declarations/scriptlets support.

**Comment by unv-unv** [comment]
Compared with plain Java: public static classes of any level aren't highlighted:
![java_nested_classes_example](https://user-images.githubusercontent.com/16825982/27798127-ca77f192-6018-11e7-9c63-535aff29eed2.png)

Example code:
```
public class Test
{
    public static class Foo
    {
        public static class Bar
        {
            public static class Baz
            {
                public static class Qux
                {
                    public static class Quux
                    {
                        public String toString() { return "Hello, World!"; }
                    }
                }
            }
        }
    }

    public static void main(String[] args)
    {
        System.out.println(new Foo.Bar.Baz.Qux.Quux());
    }
}
```

**Comment by unv-unv** [comment]
Hi! Any news?

**Comment by VISTALL** [comment]
Hi. I was busy(work). Maybe today i will check. Sorry

**Comment by VISTALL** [comment]
Looks like - i implicitly fixed this issue
