### ISSUE TITLE
Override/implement dialog doesn't suggest implementing methods of nested interface

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#19]
When I press Alt+Insert inside a nested class implementing nested interface and selecting "Override Members" Consulo doesn't suggest implementing methods of the interface:
![jsp_override_dialog_doesnt_suggest_nested_interface](https://user-images.githubusercontent.com/16825982/27711128-da6eb7de-5d2a-11e7-9c67-3389364d4731.png)

Example code:
```
<%!
interface Foo
{
    int baz();
}

public static class Bar implements Foo
{

}
%>
```

**Comment by VISTALL** [comment]
duplicate by https://github.com/consulo/consulo-javaee/issues/21

**Comment by unv-unv** [comment]
Still don't see ability to implement methods by Alt+Insert. JavaEE 2918.

**Comment by unv-unv** [comment]
Checked one more time - it was an error in my test.jsp. Implementing by Alt+Insert works fine. Thanks.
