### ISSUE TITLE
 Support for JSP declaration tags

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#2]
In complex JSP files you may have an internal declarations (custom fields of the servlet, inner classes, etc).

I have an [extreme example](https://yadi.sk/d/qklAN8T13J47Jn) of such JSP which mainly consists of internal class declarations embraced with <%! and %> tags. Such part should be treated as Java-code and syntax highlighting in Consulo seems to be aware of it. Though code inspections, refactorings and such treat this fragments as HTML code and warn about unusual HTML tags here and there.

Idea Ultimate Edition treats these parts of JSP correctly, though this functionality was not ported to Community Edition. Would be nice to have more correct support for JSP files in Consulo with JavaEE plugin installed.

Simplified code example:

```
<%@ page import="
    java.lang.*,
    java.io.*
"%>
<%!
class Test
{
    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
<%
    out.print(Test.HTML);
%>
```

Screenshot in Consulo 2.0 build 1696:

![consulo_test jsp](https://cloud.githubusercontent.com/assets/16825982/26289411/87eab076-3ea8-11e7-91f4-718c610d5b00.png)

**Comment by VISTALL** [comment]
Thanks for issue. I will review JSP impl. For now it's a stub. Be patient, it's a new implementation from a scratch

**Comment by unv-unv** [comment]
Thanks for your work :)
I've read articles about your IDE on habrahabr and now use it for simple Java classes development, though it would be great if J2EE was also supported so I may recommend it for my coleagues.

**Comment by VISTALL** [comment]
Hi. I am started working on JSP part. Now it's parse better JSP code. 

Example

![](http://klikr.org/8e4e27484dde4ac2e424c52538aa.png)

**Comment by VISTALL** [comment]
When it will pushed to release channel you can read here https://github.com/consulo/consulo/wiki/Update-channels

**Comment by unv-unv** [comment]
Great.

Could I ask one more question about plugin system? In Settings I've visited Platform and Plugins dialog. When I pressed "View available plugins" I've seen only 3 plugins all named "Platform", all having same version and updated date but different download counts. Then I've thought I cannot see already installed plugins here (though many more plugins I had not installed while installing Consulo) and removed JavaEE plugin (with dependent plugins). But after this "View available plugins" didn't show anything new - only 3 Platforms as previously.

That seems strange. So easy and convenient was initial plugin installation and so obscure how to install new plugins or update existing ones. Or existing ones are updated automatically? Then, probably, plugin list should show not only version but update date as well?

**Comment by VISTALL** [comment]
Hi. You have old build of Consulo. About -> Check for updates will update. It will update platform and plugins to new version.

I don't known your build and OS - macOS had a few update bugs in old builds (better download new Consulo build, it will be show error about plugins - then click Check for updates, and it will update plugins)

**Comment by VISTALL** [comment]
![](http://klikr.org/5bacc1c2e80e6c60ab5c6f4738db.png)

I close this complex issue. Now need create issue for each bug. 

Thanks
