### ISSUE TITLE
Class doesn't see inherited fields

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#22]
Class in JSP declaration section doesn't see inherited fields of parent class in the same declaration section:
![jsp_class_doesn t_see_inherited_fields](https://user-images.githubusercontent.com/16825982/27713366-0869ddc2-5d34-11e7-99e1-032a5600213c.png)

Example code:
```
<%!
public static class Foo
{
    public int x = 0;
}

public static class Bar extends Foo
{
    public int baz() { return x; }
}
%>

```

**Comment by VISTALL** [comment]
Strange error.

![](http://klikr.org/e949cb7f132bf37e192f122872cb.png)
