### ISSUE TITLE
JSP Formatting (Auto-indent doesn't work in JSP)

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#23]
Auto-indent (Ctrl+Alt+I) doesn't work inside JSP tags.

**Comment by VISTALL** [comment]
Hi. Formatting for JSP is not supported.

I will think about that.

Thanks

**Comment by unv-unv** [comment]
It seems to be supported partially because auto-indentation on Enter works more or less OK.

**Comment by unv-unv** [comment]
Pressing enter inside string contant creates new line shifted one space forward. So pressing enter several times produces ladder effect:

```
<%!
public static String LONG_STRING_CONSTANT = "" +
    "" +
     "" +
      "" +
       "";
%>
```

It's annoying. Could you please remove excess space? Even without full formatting support this would be helpful.

**Comment by VISTALL** [comment]
Yeah. At with week, i had expirence with editing JSP files, and it's was a pain. I wanna add something for this.
But for now - i am trying to fix bad issue with anti-virus (https://discuss.consulo.io/t/import-vs-2015-project/72/25)

Thanks

**Comment by VISTALL** [comment]
Hello. Playing with formatting. Searching way for make smart enter more usable (disabling formatting not fix issue with enter, but suppress other formatting issues)

Thanks

**Comment by unv-unv** [comment]
Any news? Still annoying 1 space indent on Enter. Even other formatting issues in JSP aren't so annoying than this 1 space indent.

**Comment by VISTALL** [comment]
Hello. I tested few variants of this implementation, but result was unacceptable and i switched to another issue (i'm always switching to another issues, due don't wanna lose time (better fix other issues in one week - not one).

Sorry. I add this issue to July short list (https://github.com/orgs/consulo/projects/8). In this month i'm not sure can i return to it, since i fired  - and searching new job.

Thanks

**Comment by VISTALL** [comment]
Sorry for delay. Playing with it

**Comment by VISTALL** [comment]
Good day sir :)

I'm added test implementation of java+xml formatting support in jsp files. Feel free to test it in nightly channel.

Thanks

**Comment by unv-unv** [comment]
Great! Thanks! I'll test it as soon as possible.

**Comment by unv-unv** [comment]
It seems that JSP formatting is working well. Many thanks.

Though Subversion plugin doesn't work in last nightly release: I needed to uninstall plugin to make everything working instead of showing blank screen with "loading" icon rotating in project browser.

**Comment by VISTALL** [comment]
Hello. Thanks i will check it.

**Comment by VISTALL** [comment]
Fixed
