### ISSUE TITLE
Duplicate annotation error on nested annotations

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#24]
If I declare nested annotation and use more than one (different) nested annotation per method then duplicate annotation error is shown:
![jsp_duplicate_annotation_error_on_nested_annotations](https://user-images.githubusercontent.com/16825982/27891371-24d0c912-6202-11e7-8d91-7f4f263e5e53.png)

In normal Java class this works correctly - error is JSP only.

Example code:
```
<%@ page import="
    java.lang.annotation.*,
"%>
<%!
@Target({ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Annotation1 {}

@Target({ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Annotation2 {}

public static class Foo
{
    @Annotation1
    @Annotation2
    int bar();
}
%>
```

**Comment by VISTALL** [comment]
reopened - have some bug on edit

**Comment by VISTALL** [comment]
fixed
