### ISSUE TITLE
Syntax analysis cycles in large JSP files

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#28]
Example of file where syntax analysis often starts to cycle (constantly loading processor): https://yadi.sk/d/D_rrPFfFc-mKeQ

Video of syntax analysis cycling (goes up from 0% to 19% or 20%, then resets and repeats): https://yadi.sk/i/AQkRYBIao5Ea-w

**Comment by VISTALL** [comment]
Hello. Can you attach log file?

**Comment by unv-unv** [comment]
[consulo.log](https://github.com/consulo/consulo-javaee/files/3269923/consulo.log)

**Comment by VISTALL** [comment]
Hello. I tested it, but there no problems. I'm unsure - but i saw in log stub error , can you Invalidate cache? (i want catch this error - but no success)

Will be nice, if you try open db file after invalidate.

Thanks

**Comment by VISTALL** [comment]
Found assert problem. Working on it

**Comment by VISTALL** [comment]
pushed commit, which fix assertion.  Test it:)

**Comment by unv-unv** [comment]
It seems I've forgotten to answer here. Yes, the problem was fixed, thanks.
