### ISSUE TITLE
"Cannot access class" error within JSP declaration

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#29]
Some rows randomly highlighted by "Cannot access class" error. Classes are declared within the same JSP declaration tag. JSP is syntactically correct (server executes it OK).
![изображение](https://user-images.githubusercontent.com/16825982/66253699-c17e1900-e774-11e9-8523-4ca962256a35.png)

**Comment by VISTALL** [comment]
Hello. Reproduced. Working on fix
