### ISSUE TITLE
Java code isn't highlighted in JSP

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#3]
JavaEE plugin version 2320. Installed plugins:
![plugins_installed](https://user-images.githubusercontent.com/16825982/26878219-5cf650c4-4b95-11e7-9e1d-b548f9b73724.png)

Follow up for issue #2.

Java code is now partially recognized as Java code (no warnings about HTML tags within Java code, simple refactorings work correctly). Though Java code isn't highlighted:
![jsp_java_code_isn t_highlighted](https://user-images.githubusercontent.com/16825982/26878316-c1816a60-4b95-11e7-9e88-2cb67bbe68a8.png)

JSP code:
```
<%@ page import="
    java.lang.*,
    java.io.*
"%>
<%!
class Test
{
    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
<%
    out.print(Test.HTML);
%>
<html>
<head><title>Hello, World!</title></head>
<body><div>Hello, World!</div></body>
</html>
```

**Comment by VISTALL** [comment]
Hm. Looks like something broken. I will check. I am confused

Thanks

**Comment by VISTALL** [comment]
Hm.


![](http://klikr.org/4f82608e1958b8415ef7deb03a33.png)

Can you say JavaEE plugin version?

**Comment by VISTALL** [comment]
Actual?

**Comment by unv-unv** [comment]
Much better now:
![jsp_java_code_isn t_highlighted_2](https://user-images.githubusercontent.com/16825982/27247142-e5395b3c-52fe-11e7-9ee9-1bcbd892dd4b.png)

Hightlighting identifiers under cursor now works (as shown on screenshot above). Though Java syntax highlighting still doesn't work: keywords aren't highlighted, literals aren't highlighted, etc.

Strange highlighting of HTML tags is gone. Though HTML tags aren't highlighted under cursor (< and > are highlighted).

**Comment by VISTALL** [comment]
Can you say name of your Color Scheme ? Or attach it (from ${system-drive}/Users/${user-name}/AppData/Roaming/Consulo/colors/$name$.ics)

Looks like its darcula - will test

**Comment by VISTALL** [comment]
reproduced

**Comment by unv-unv** [comment]
Thanks - highlighting now works.
