### ISSUE TITLE
Clicking on JSP file in project tree — nothing happens

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#31]
Click on JSP file doesn't open a tab with this file.

**Comment by VISTALL** [comment]
Looks like due internal error. Must be fixed in nightly. Sorry, idk how i missed that :(

**Comment by VISTALL** [comment]
If not help - please attach log file

**Comment by unv-unv** [comment]
Seems that fix helped — can open JSP now. Thanks.

**Comment by VISTALL** [comment]
Thanks
