### ISSUE TITLE
HTML tags are strangely highlighted in JSP

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#4]
JavaEE plugin version 2320. Installed plugins:
![plugins_installed](https://user-images.githubusercontent.com/16825982/26878219-5cf650c4-4b95-11e7-9e1d-b548f9b73724.png)

HTML tags are strangely hightlighted (note grey color of "e" in </title> and ">" in <head>, </head> and </body>):
![jsp_java_code_isn t_highlighted](https://user-images.githubusercontent.com/16825982/26878316-c1816a60-4b95-11e7-9e88-2cb67bbe68a8.png)

JSP code:
```
<%@ page import="
    java.lang.*,
    java.io.*
"%>
<%!
class Test
{
    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
<%
    out.print(Test.HTML);
%>
<html>
<head><title>Hello, World!</title></head>
<body><div>Hello, World!</div></body>
</html>
```

**Comment by VISTALL** [comment]
I think is duplicate by https://github.com/consulo/consulo-javaee/issues/3. Due something broken.
