### ISSUE TITLE
JSP imports are ignored

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#7]
Class declarations aren't analyzed against JSP imports:
![jsp_doesn t_see_declaration](https://user-images.githubusercontent.com/16825982/27314633-cd5f5bca-557d-11e7-870b-a286cbad7438.png)

Example code (Array shoulde be linked to java.lang.reflect.Array):
```
<%@ page import="
    java.lang.*,
    java.lang.reflect.*,
    java.io.*
"%>
<%!
public static <E> E[] array(Collection<? extends E> col, Class<E> clazz)
{
    if (col == null) return null;
    E[] arr = (E[])Array.newInstance(clazz, col.size());
    return col.toArray(arr);
}

public static enum TestEnum {FIRST, SECOND, THIRD};
class Test
{
    public static final String HTML = "<html>\n" +
    "<head><title>Hello, World!</title></head>" +
    "<body><div>Hello, World!</div></body>\n" +
    "</html>";
}
%>
<%
    out.print(Test.HTML);
%>
<html>
<head><title>Hello, World!</title></head>
<body><div>Hello, World!</div></body>
</html>
```

Note that there may be several page tags with import directives. So import section may look like:
```
<%@ page import="java.lang.*"%>
<%@ page import="java.lang.reflect.*"%>
<%@ page import="java.io.*"%>
```

**Comment by VISTALL** [comment]
hm. should work

**Comment by VISTALL** [comment]
![](http://klikr.org/f114332f4f0a3e5d152b1ffd5652.png)

**Comment by VISTALL** [comment]
Can you enabled Java + JSP module extension ? (and move it under source directory)

**Comment by VISTALL** [comment]
I found issue with Add Import. Working on it (throw exception on add action)

**Comment by unv-unv** [comment]
As I remember, commercial Idea prefers creating separate page tag per each import but recognizes both import forms.

**Comment by VISTALL** [comment]
I will check sepature tags - after Add Import fix

**Comment by unv-unv** [comment]
Also I don't understand why syntax error highlighting doesn't work for me as it works for you (highlighting Collection). Is it another Darcula issue?

**Comment by VISTALL** [comment]
Looks like your files are out of project (java file & jsp files must be inside source & webapp directories) - or they will block all errors.

**Comment by VISTALL** [comment]
![](http://klikr.org/f27bba82a8012b345f25d1108ab7.png)

![](http://klikr.org/afc4778949b679843d21396c98e7.png)

**Comment by unv-unv** [comment]
Understood. Though I created my project as Console Application and don't have button for marking folder as WebApp. There probably should be another project template for it. Though project template selection on project creation doesn't contain JavaEE project, instead it contains two templates named "Empty" - I've created one more issue: https://github.com/consulo/consulo-java/issues/72

**Comment by VISTALL** [comment]
Enable JSP extension in extensions. And "web directory" action will appear

**Comment by unv-unv** [comment]
It worked. Thanks.

**Comment by VISTALL** [comment]
Good. Almost all "language, frameworks, etc" settings can be enabled or disabled in Extensions (not like IDEA style)

**Comment by VISTALL** [comment]
Tests. It work as expected 

![](http://klikr.org/dd67f0aeba598df8473e97b7d525.png)

**Comment by VISTALL** [comment]
And Add Import action fixed too.
