### ISSUE TITLE
Implicit object pageContext should be supported

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-javaee#9]
The following code should show no errors but now pageContext is highlighted:
```
<%
    pageContext.getRequest().setCharacterEncoding("UTF-8");
%>
```

[Other implicit objects](http://www.tutorialspoint.com/jsp/pdf/jsp_implicit_objects.pdf) seem to be supported correctly.

**Comment by VISTALL** [comment]
Thanks. It's my mistake (**pageContext** not **context** field)
